export default [
	{
		training_id: 1,
		client_id: 123,
		goal: {
			id: 456,
			client_id: 123,
			status: "IN PROGRESS",
			descriptionGoal: "Reduce body fat by 10% in 3 months",
			timeLapse: "3",
			timeUnit: "months",
			percentage: "10%",
			goalType: "LOSE WEIGHT",
			healthyFocusDescription:
				"Focus on high-intensity interval training and clean eating",
			trainerPlans: "MUSCLE",
			nutritionistPlans: "HEALTH WEIGHT",
			dietStatus: "IN PROGRESS",
			trainingStatus: "IN PROGRESS",
			init_on: "2024-03-01",
			end_on: "2024-05-31",
			created_on: "2024-02-15",
			updated_on: "2024-03-20",
			isCompleted: false,
		},
		coach_id: 789,
		customForm_id: 101,
		coach_plans: "MUSCLE",
		training_status: "IN PROGRESS",
		type: "LOSE WEIGHT",
		description_training:
			"High-intensity interval training with focus on cardio and strength",
		exercise: "Burpees, Squats, Deadlifts",
		exercise_description: "Perform 3 sets of 10 reps for each exercise",
		series: "3",
		repetitions: "10",
		amount_of_days: "5",
		frequency: "Daily",
		init_on: "2024-03-01",
		end_on: "2024-03-31",
		created_on: "2024-02-20",
		updated_on: "2024-03-25",
		isCompleted: false,
		isActive: true,
	},
	{
		training_id: 2,
		client_id: 456,
		goal: {
			id: 456,
			client_id: 123,
			status: "IN PROGRESS",
			descriptionGoal: "Reduce body fat by 10% in 3 months",
			timeLapse: "3",
			timeUnit: "months",
			percentage: "10%",
			goalType: "LOSE WEIGHT",
			healthyFocusDescription:
				"Focus on high-intensity interval training and clean eating",
			trainerPlans: "MUSCLE",
			nutritionistPlans: "HEALTH WEIGHT",
			dietStatus: "IN PROGRESS",
			trainingStatus: "IN PROGRESS",
			init_on: "2024-03-01",
			end_on: "2024-05-31",
			created_on: "2024-02-15",
			updated_on: "2024-03-20",
			isCompleted: false,
		},
		coach_id: 789,
		customForm_id: 102,
		coach_plans: "RITMIA",
		training_status: "COMPLETED",
		type: "INCREASE MASS MUSCLE",
		description_training:
			"Strength training with emphasis on compound exercises",
		exercise: "Squats, Bench Press, Deadlifts",
		exercise_description: "Perform 4 sets of 8 reps for each exercise",
		series: "4",
		repetitions: "8",
		amount_of_days: "4",
		frequency: "Every other day",
		init_on: "2024-02-01",
		end_on: "2024-03-31",
		created_on: "2024-01-20",
		updated_on: "2024-04-05",
		isCompleted: true,
		isActive: false,
	},
];
