import {
	DietStatus,
	NutritionistPlansServices,
	TypeDiets,
} from "@/interfaces/diets";
import { GoalStatus, TypeGoals } from "@/interfaces/goals";
import { CoachPlansServices, TrainingStatus } from "@/interfaces/trainings";

export default [
	{
		diet_id: 1,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.STARTED,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.HIPERTROFIA,
		nutritionist_plans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
		diet_status: DietStatus.IN_PROGRESS,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.LOSE_WEIGHT,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "✦ Manzana verde \n✦ Apio \n✦ Perejil",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 6,
		duration: "6 meses",
		init_on: "2024-03-01",
		end_on: "2024-09-01",
		created_on: "2024-02-01",
		isCompleted: false,
		isActive: true,
	},
	{
		diet_id: 2,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.HIPERTROFIA,
		nutritionist_plans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
		diet_status: DietStatus.COMPLETED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: true,
		isActive: false,
	},
	{
		diet_id: 3,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.MUSCLE,
		nutritionist_plans: NutritionistPlansServices.HEALTH_WEIGHT,
		diet_status: DietStatus.CANCELED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: false,
		isActive: false,
	},
	{
		diet_id: 4,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.MUSCLE,
		nutritionist_plans: NutritionistPlansServices.HEALTH_WEIGHT,
		diet_status: DietStatus.CANCELED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: false,
		isActive: false,
	},
	{
		diet_id: 5,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.MUSCLE,
		nutritionist_plans: NutritionistPlansServices.HEALTH_WEIGHT,
		diet_status: DietStatus.CANCELED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: false,
		isActive: false,
	},
	{
		diet_id: 6,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.MUSCLE,
		nutritionist_plans: NutritionistPlansServices.HEALTH_WEIGHT,
		diet_status: DietStatus.CANCELED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: false,
		isActive: false,
	},
	{
		diet_id: 7,
		client_id: 2,
		nutritionist: 456,
		custom_form: 789,
		goal: {
			id: 1,
			client_id: 2,
			status: GoalStatus.IN_PROGRESS,
			descriptionGoal:
				"Reducir un 8% del peso corporal en los próximos seis meses de manera sostenible y saludable.",
			timeLapse: "6",
			timeUnit: "meses",
			percentage: "8%",
			goalType: TypeGoals.LOSE_WEIGHT,
			healthyFocusDescription:
				"Enfocado en una alimentación balanceada y hábitos saludables.",
			trainerPlans: CoachPlansServices.HIPERTROFIA,
			nutritionistPlans: NutritionistPlansServices.HEALTHY_EAT_AND_LOSE_WEIGHT,
			dietStatus: DietStatus.STARTED,
			trainingStatus: TrainingStatus.IN_PROGRESS,
			init_on: "2024-03-01",
			end_on: "2024-09-01",
			created_on: "2024-02-01",
			updated_on: "2024-03-15",
			isCompleted: false,
		},
		trainer_plans: CoachPlansServices.MUSCLE,
		nutritionist_plans: NutritionistPlansServices.HEALTH_WEIGHT,
		diet_status: DietStatus.CANCELED,
		training_status: TrainingStatus.IN_PROGRESS,
		type: TypeDiets.INCREASE_MASS_MUSCLE,
		description_diet:
			"Plan de alimentación para perder peso de forma saludable.",
		balanced_meal_plan: "Plan equilibrado con nutrientes esenciales.",
		portion_size_guide: "Guía de tamaños de porción adecuados.",
		healthy_shopping_list: "Lista de compras saludables.",
		healthy_recipes: "Recetas saludables y deliciosas.",
		tips_for_change_eating_habits:
			"Consejos para cambiar hábitos alimenticios.",
		nutrition_information: "Información nutricional detallada.",
		hydratation: "Recomendaciones para una adecuada hidratación.",
		food_education: "Educación alimentaria para una dieta balanceada.",
		longTimeInMonths: 3,
		duration: "3 months",
		init_on: "2024-01-01",
		end_on: "2024-03-01",
		created_on: "2024-01-01",
		isCompleted: false,
		isActive: false,
	},
];
